### ISSUE TITLE
Add support for 112, 128, and 160 curves

### ISSUE THREAD

**Issue by corywright** [tlsfuzzer/python-ecdsa#24]
I would like to use python-ecdsa to produce keys that are compatible with the [ellipticlicense](https://github.com/vslavik/ellipticlicense) project.  This project uses 112, 128, and 160 bit curves to produce license keys that, while less secure, are smaller and thus more suitable for that use case.

Would there be any interest from the developers here to add 112, 128, and/or 160 bit curves to python-ecdsa?

**Comment by opoplawski** [comment]
Note that openssl in Fedora does not support curves less than 256 bits because they are considered insecure.  See https://bugzilla.redhat.com/show_bug.cgi?id=1067697.  If you do support these, it would be good to do it in a way that recognizes that the underlying openssl may not support them and disable them in that case.

**Comment by tomato42** [comment]
Unlike OpenSSL, ecdsa can add them without need to change set of ones supported by default.

Also, security guarantees of ecdsa are weaker.

**Comment by tomato42** [comment]
For the record, the curves in question are `secp112r1`, `secp128r1` and `secp160r1`, the parameters of which can be found in https://www.secg.org/SEC2-Ver-1.0.pdf, pages 6 to 10. They're also supported by OpenSSL so we can easily test interoperability.
