### ISSUE TITLE
"'Curve' object has no attribute 'p'" in recover_public_keys()

### ISSUE THREAD

**Issue by opacey** [tlsfuzzer/python-ecdsa#319]
When calling:

```
generatorPoint = ecdsa.ellipticcurve.PointJacobi(SECP256k1, secp256k1_generator_x, secp256k1_generator_y, 1, secp256k1_group_order, True)
sig = ecdsa.ecdsa.Signature(r, s)
pubkey1, pubkey2 = sig.recover_public_keys(message, generatorPoint)
```

I get the error:

```
Traceback (most recent call last):
  File "sig2pubkey.py", line 100, in <module>
    pubkey1, pubkey2 = sig.recover_public_keys(message, generatorPoint)
  File "~/.local/lib/python3.10/site-packages/ecdsa/ecdsa.py", line 113, in recover_public_keys
    pow(x, 3, curve.p()) + (curve.a() * x) + curve.b()
AttributeError: 'Curve' object has no attribute 'p'
```

Indeed the `Curve` object does not have a `p` attribute, but it does contain an `ecdsa/ellipticcurve/CurveFp()` object (named `curve_secp256k1` in my case) which has a `p` attribute.

Could this be a bug? If not I'd be v grateful for any tips on how to fix my own code!

**Comment by tomato42** [comment]
Why you're constructing those objects manually?

VerifyingKey has two APIs to create them from signatures:
https://github.com/tlsfuzzer/python-ecdsa/blob/2457dc7c9b7337edcb868a323c5b648a32da2b8c/src/ecdsa/keys.py#L415
and
https://github.com/tlsfuzzer/python-ecdsa/blob/2457dc7c9b7337edcb868a323c5b648a32da2b8c/src/ecdsa/keys.py#L467

What you're trying to do doesn't work because PointJacobi doesn't expect `Curve` objects, it expects the low level `CurveFp` objects, as specified in documentation:
https://github.com/tlsfuzzer/python-ecdsa/blob/2457dc7c9b7337edcb868a323c5b648a32da2b8c/src/ecdsa/ellipticcurve.py#L509

**Comment by opacey** [comment]
I have the hash of a signed message, and the signature itself. I wish to recover the pubkey from that sig. I am not trying to verify  the sig which is why it didn't occur to me to try that route. Thanks for the tips, though, is `VerifyingKey` the correct way to approach the solution?

**Comment by tomato42** [comment]
both `message` and `sig` are hex encoded, while you're passing them as-is; you need to convert the hex characters to bytes

**Comment by opacey** [comment]
THANK YOU. I thought I'd done that already so gave myself a blind spot. Really appreciate the help. I now have the code I need.
